### ISSUE TITLE
Excluded stuff for got:inspect

### ISSUE THREAD

**Issue by ostrolucky** [swisnl/game-of-tests-laravel#1]
On https://github.com/swisnl/game-of-tests-laravel/blob/64caf0bb919b7b50ad083031e33b1699d7fe64c3/src/Console/Commands/InspectUrl.php#L69 you are excluding lot of important info, which makes final stats useless, why?

**Comment by bbrala** [comment]
Hi, thanks for checking the library out. What info are you missing?

**Comment by ostrolucky** [comment]
author, date, etc

**Comment by bbrala** [comment]
The Results should contain the following data:

From the migration:

```
$table->increments('id'); 
$table->string('remote'); // remote url to repository
$table->string('filename')->index('results_file_index'); // file containing tests
$table->string('line'); // line in file
$table->string('author')->index(); // author given for ocmmit
$table->string('author_normalized')->index('author_normalized'); // normalized name for grouping
$table->string('author_slug'); // slug based on normalized author name
$table->string('email'); // author email
$table->string('date'); // commit date unix timestamp
$table->string('commitHash');  // hash of commit
$table->string('parser'); // which parser was used
$table->timestamps(); // created at (when was commit done), updated at (last update of row)
$table->unique(['remote','filename','line'], 'results_remote_file_line_unique');
$table->index(['email','filename'], 'results_email_file_index');
```

**Comment by ostrolucky** [comment]
On the line I posted you are excluding everything except `['remote', 'filename', 'line']`

**Comment by bbrala** [comment]
No, the line checks for an existing record using only those 3 fields. The rest is also passed and fully inserted or updated. See the method [updateOrCreate](https://github.com/swisnl/game-of-tests-laravel/blob/b2528d48fed68ddde67ef532f2f87c406d8c00c0/src/Models/Results.php#L20) in the Results model.
