### ISSUE TITLE
got:inspect: Couldnt insert: filename

### ISSUE THREAD

**Issue by ostrolucky** [swisnl/game-of-tests-laravel#2]
This line https://github.com/swisnl/game-of-tests-laravel/blob/64caf0bb919b7b50ad083031e33b1699d7fe64c3/src/Console/Commands/InspectUrl.php#L69 throws `Illuminate\Database\Eloquent\MassAssignmentException` (which you are  obfuscating for some reason, but whatever)

It seems you need to specify in your model which fields can be filled, or disable this eloquent protection

**Comment by bbrala** [comment]
Hmm, yeah thought i added a unguard for the time being, i'll have a look why it isn't there. Thanks for reporting.

**Comment by bbrala** [comment]
I've added unguard to the command for now, will need to just add the fillable property to the model at some point. Will keep this open for now.

**Comment by bbrala** [comment]
Fixed in 1.0, had that change in my respository for ages, but forgot it commit and push. :(
